name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
        laravel:
          - 8.*
        prefer:
          - 'prefer-lowest'
          - 'prefer-stable'
        include:
          - laravel: '8.*'
            testbench: '6.*'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} --${{ matrix.prefer }}

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Setup CockroachDB Cluster
      run: |
        docker network create -d bridge roachnet
        docker run -d --name=roach1 --hostname=roach1 --net=roachnet -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v21.1.5 start --insecure --join=roach1,roach2,roach3
        docker run -d --name=roach2 --hostname=roach2 --net=roachnet cockroachdb/cockroach:v21.1.5 start --insecure --join=roach1,roach2,roach3
        docker run -d --name=roach3 --hostname=roach3 --net=roachnet cockroachdb/cockroach:v21.1.5 start --insecure --join=roach1,roach2,roach3
        docker exec roach1 ./cockroach init --insecure
        until curl --silent -XGET --insecure --fail http://127.0.0.1:8080/health; do printf '.'; sleep 1; done

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: pcov

    - uses: actions/cache@v3.0.1
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "orchestra/database:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.prefer }} --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: |
        vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

    - uses: codecov/codecov-action@v2.1.0
      with:
        fail_ci_if_error: false
